### ISSUE TITLE
Einbinden Videos von uns

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#12]
Wie werden die Videos eingebunden, die wir im Projekt produziert haben (von Tanja etc)? Eigener LoG YouTube Kanal? Oder eigener Kanal von den Erstellerinnen zum Einbinden? Habt ihr das schon fixiert?

**Comment by leganz** [comment]
@natiie es gibt zwei Möglichkeiten
=> video posten
=> oder wenn wir channel watching noch implementieren wollen => dann in den channel-watch aufnehmen.
=> oder was jetzt geht => Administrator den LoG Youtube Account hinterlegen, dann wird es sobald der Cronjob läuft berücksichtigt

**Comment by leganz** [comment]
@natiie @monotonist bei Seiten können ebenfalls Videos einbunden werden.
