### ISSUE TITLE
News Typ "News Artikel"

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#13]
Bei News einreichen wäre eine Kategorie "News Artikel" gut. Darunter würde dann z.b. orf.at Artikel fallen oder auch in Zukunft Pressemeldungen zum Projekt oder zum Thema

**Comment by leganz** [comment]
Fällt eigentlich unter die Kategorie (Blog)
@natiie

**Comment by natiie** [comment]
Ok passt
