### ISSUE TITLE
MEET Profil Plattformen etc

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#15]
Hier sollts ja dann noch mehr Plattformen u Kommunikationsmöglichkeiten zur Auswahl geben. Brauchst du da noch eine Liste?

**Comment by leganz** [comment]
@natiie ja ich brauch nur eine liste
=> ist alles dynamisch via datenbank erweiterbar und verwaltbar.

**Comment by natiie** [comment]
Ok ich fang hier mal Liste an - bitte dann noch ergänzen:

Kommunikation:
Skype
Discord
Teamspeak
Was sind da die gängigsten? Kenn mich nicht so aus

Plattformen
PC
PlayStation
Xbox
Mobile

Links und Profile
Twitch
Twitter
YouTube
Facebook
Web (--> für allgemeine Links, z.B. eigene Webseite)

**Comment by leganz** [comment]
@monotonist, @natiie  bitte testen
Admin-Konto kann neue Spiele, Plattformen, Linktypen, Kommunikationsmethoden hinzufügen
