### ISSUE TITLE
Eintrag von Twitch Channel hat nicht funktioniert 

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#16]
Soll hier User oder Link angegeben werden? Beides nicht geklappt

**Comment by leganz** [comment]
Channelnamen müssen angegeben werden z.B. https://www.twitch.tv/limesodacrew => limesodacrew
Bitte beachten, dass beim News-Submit nur Channels submitted werden können, die live sind, da sonst die Punktevergabe irgendwie absurd wäre.

Mit dem nächsten Update gibts dazu auch noch eine Fehlermeldung wenn dies der Fall ist.

**Comment by leganz** [comment]
Bitte testen
