### ISSUE TITLE
Liste für Crawler (Twitch, YT Gaming, Twitter Hashtags)

### ISSUE THREAD

**Issue by monotonist** [PICAPIPE/league-of-girls#19]
Einbindung von Twitch/YT Gaming/Hashtags über eine einfache Liste ohne Registrierung.

**Comment by leganz** [comment]
@monotonist bitte testen.

**Comment by natiie** [comment]
War das jetzt das mit dem Crawler Einstellungen über das Admin Konto? Oder noch etwas anderes? Je nachdem schließen oder nicht ;)

**Comment by leganz** [comment]
Ja ursprünglich war ein Google Sheets File angedacht aber der Menüpunkt erledigt es besser.
