### ISSUE TITLE
Neue Channels (Overwatch, Fortnite)

### ISSUE THREAD

**Issue by monotonist** [PICAPIPE/league-of-girls#20]
Neue Channels für: Overwatch & Fortnite

**Comment by leganz** [comment]
@monotonist, @natiie  bitte testen
Admin-Konto kann neue Spiele, Plattformen, Linktypen, Kommunikationsmethoden hinzufügen

**Comment by monotonist** [comment]
ok danke

**Comment by monotonist** [comment]
Beim Hinzufügen kommt die Meldung, dass ich aktuell dafür keine Berechtigung habe
