### ISSUE TITLE
Einbinden von Inhalten ohne Zuordnung

### ISSUE THREAD

**Issue by monotonist** [PICAPIPE/league-of-girls#21]
Einbinden ("News Einreichen") ohne konkrete Spielzuordnung (= allgemein)

**Comment by leganz** [comment]
@monotonist, @natiie  bitte testen

**Comment by monotonist** [comment]
geht aktuell nicht - getestet mit: 

https://youtu.be/oTc0Qus92K8

Trying to get property of non-object

**Comment by natiie** [comment]
Hat bei mir jetzt funktioniert. Hab die YouTube ID eingegeben, nicht den Link. Vielleicht lags daran.
