### ISSUE TITLE
Introtext

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#28]
Bitte den Introtext auf die Startseite:

“League of Girls” rückt Spielerinnen ins Zentrum und gibt Einblicke in die weibliche Gaming Szene. Unser Schwerpunkt liegt dabei auf E-Sport und Streaming, wobei jedoch alle Beiträge rund um Gaming willkommen sind. Werdet Teil der “League of Girls” Community und helft uns dabei, E-Sport stärker in der Gesellschaft zu verankern - female AND male players are welcome!

**Comment by leganz** [comment]
Bitte testen.
