### ISSUE TITLE
Text bei News einreichen

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#29]
Oben den Text beim Formular bitte mit folgendem Text austauschen:

In unserer News-Sektion veröffentlichen wir Beiträge, die mit der weiblichen E-Sport & Gaming Szene in Verbindung stehen. Eingereicht werden können z.B. Blog- & News-Artikel oder Beiträge aus Social Media und Streaming Kanälen. Bitte fülle alle Felder aus. Die Kurzbeschreibung erscheint in der Preview des Artikels. Nach der Einreichung wird der Artikel von unserer Redaktion überprüft und freigeschaltet.

**Comment by leganz** [comment]
Bereit zum Testen.
