### ISSUE TITLE
Username bei Plattformen

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#31]
Macht bei den Plattformen der Username Sinn? Würde den hier eher weg, also reine Angabe auf welcher Plattform man spielt.
Aktuell hätte ich folgende reingenommen;
PlayStation
Xbox
PC
Mobile

**Comment by leganz** [comment]
@natiie das Problem an diesem Punkt ist, dass ich für dafür die Logik ändern muss. Weil der Inhalt darin für den "Status" Aktiv/Inaktiv herangezogen wird. Außerdem war bei Plattformen soweit ich aus den Mockups erkennen konnte eher Playstation Network, Steam etc. gemeint soweit ich weiß.

ich hab es mal als won't fix gekennzeichnet - sollten also noch darüber diskutieren.

**Comment by leganz** [comment]
Ok wenn es so passt dann closen wir mal.
