### ISSUE TITLE
Gibts es eine Möglichkeit die Angaben bei News-Beiträgen im Nachhinein zu bearbeiten?

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#32]
Wäre vielleicht gut, wenn Admin hier noch etwas ändern kann. Oder geht das eh irgendwie?

**Comment by leganz** [comment]
Admins können nun bei den jeweiligen Einträgen in den Bearbeitungsmodus wechseln oder den Eintag sogar löschen. @natiie bitte testen.

**Comment by natiie** [comment]
super
