### ISSUE TITLE
Icons teils nicht angezeigt

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#34]
Bei der Teamspeak (Kommunikationsmethode) und Website (Links) wird das Icon nicht angezeigt. Css Klasse dürfte aber die richtige sein.

**Comment by leganz** [comment]
Liegt an der Tatsache, dass wir eine ältere Font-Aweseome Version verwendet haben. 
Im nächsten Update werden wir das so implementieren, dass stets die aktuellste Version geladen wird.

**Comment by leganz** [comment]
Bitte testen.
