### ISSUE TITLE
"Keine weiteren Daten gefunden" 

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#4]
Meldung "Keine weiteren Daten gefunden" bei Klick auf Spiele bei MEET kommt mehrere Male.

**Comment by leganz** [comment]
@natiie bitte testen

**Comment by natiie** [comment]
Kommt noch immer vor. Bei Klick auf die Spiele (unabhängig vom gewählten Bereich), hier z.B. bei NEWS:

![grafik](https://user-images.githubusercontent.com/41503397/43569364-8545a85c-9637-11e8-8977-66a4836cd82a.png)

**Comment by leganz** [comment]
@natiie bitte testen.
