### ISSUE TITLE
Geteilt von ... "a few seconds ago"

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#41]
Bei der Zeitangabe bei den NEWS Beiträgen steht immer "a few seconds ago" - auch wenn der Beitrag schon länger geteilt wurde.

Die Schrift ist hier auch kaum leserlich, am besten etwas dünkler / größer

**Comment by leganz** [comment]
Sollte jetzt korrekte Zeitspanne angeben. @natiie
