### ISSUE TITLE
Keine Chat Möglichkeit bei Twitter Beiträgen

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#43]
Ist das beabsichtigt?

**Comment by leganz** [comment]
Nein ist natürlich nicht beabsichtigt. Fehlerkorrektur ist am Server. Es gibt nun im Code auch einen eigenen Terminalbefehl "php artisan chat:update" um fehlende Newseinträge zu erfassen.

@natiie bitte testen.

**Comment by natiie** [comment]
Seltsam, also Chat scheint jetzt bei allen Twitter Beiträgen auf, nur beim letzten der momentan gepostet ist nicht. (missmadhatx - KÖLSCH wir kommen :D ...)
