### ISSUE TITLE
Unterstützer*innen Liste

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#45]
@PICAPIPE/picapipe Wollen wir so etwas wie eine Unterstützer*innen-Liste auf der Seite? Kann ein einfacher Menüpunkt sein, mit Organisationen, Personen in der Szene, die unsere Initiative unterstützen. ESVÖ z.B. 

mit:

Name Organisation
evtl. Statement zur Förderung von Frauen im E-Sport?
Link zur Organisation

Entweder wir sammeln Unterstützer oder/und es gibt Funktion, wo man das selbst eintragen kann.
Also mal so als Idee. Wäre halt für Credibility gut.

**Comment by leganz** [comment]
Könnte man das nicht sogar eine "Liste" von "Teams"/"Organisationen" etc. erweitern?
Je mehr Anknüpfungspunkte man hat desto besser für die komplette Szene oder?

@natiie @monotonist

**Comment by leganz** [comment]
Hab mal die Punkte für den nächsten Meilenstein markiert.

**Comment by leganz** [comment]
Es gibt auf der Seite noch eine statische Seite zu Partnern. Diese wird von PICAPIPE momentan fortlaufend ergänzt.
