### ISSUE TITLE
Aktionen Menü auf Startseite (nach Login) 

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#5]
Aktionen Sektion neben News und Meine News auf der Startseite (eingeloggt) würde ich weg (Impressum etc. ist dann ja auch als Menüpunkt aufzufinden)

**Comment by leganz** [comment]
@natiie der Bereich ist eigentlich bisschen als Place to be für Navigationseleme gedacht die dann inhaltlich sonst nirgends reinpassen. Also ein Platzhalter

**Comment by natiie** [comment]
Glaube die Seiten wären alle am besten in der Menüleiste unten. Sonst wird es zu übersichtlich und es werden glaube ich insgesamt ohnehin nicht viele Seiten werden.
Also ich würde das Aktionen Menü eigentlich nach wie vor weg. Aber bitte noch um Meinung von euch.

**Comment by leganz** [comment]
Siehe #6  => Menü ist nach unten gewandert.

**Comment by natiie** [comment]
👍
