### ISSUE TITLE
Überarbeitung Welcome Page

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#54]
Welcome Page sollte noch etwas ansprechender werden und klarer machen, was wir mit LoG erreichen wollen. @Gitsack Am besten du schaust da mal drüber. :) 

Feedback von Yvonne:

Eine übersichtliche Welcome-Seite sollte implementiert werden. Mehr als bereits vorhandener Text „Was ist „League of Girls” – LoG rückt Spielerinnen ins Zentrum und gibt Einblicke in die weibliche Gaming Szene. Unser Schwerpunkt liegt dabei auf E-Sport und Streaming, wobei jedoch alle Beiträge rund um Gaming willkommen sind. Werdet Teil der “League of Girls” Community und helft uns dabei, E-Sport stärker in der Gesellschaft zu verankern - female AND male players are welcome“ Ziele ergänzen? 
Stichworte: Zusammenhalt, Aufbau community, Gleichberechtigung, welche Rubriken gibt es bei unserer Seite, was bringt es mir wenn ich mich anmelde, positiv motivierend textieren, …

Grundfrage: ausschließlich Gamerinnen aus der DACH Region?

**Comment by leganz** [comment]
@Gitsack  hat hier tolle Arbeit geleistet und die Startseite komplett überarbeitet. Es kommen nun auch Videos in Endlosschleifen zum Zug.
