### ISSUE TITLE
Origin und Nintendo Icon

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#57]
Hab Origin und Nintendo als Plattformen dazugefügt. Es gibt aber keine Font Awesome Icons dazu. Hab mal etwas halbwegs Passendes genommen, aber da brauchen wir noch bald die richtigen Icons.

**Comment by leganz** [comment]
Es liegt für beide Unternehmen leider ein Schreiben vor, dass wir dies Icons nicht verwenden können. Damit wird es geclosed.
