### ISSUE TITLE
Fortgeschritten falsch geschrieben bei Auswahl Spiele im Profil

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#59]
Feedback von Yvonne:
Spiele – Unterteilung in Anfänger – Profi finde ich interessant, allerdings ist Fortgeschritten falsch geschrieben – evtl. hier besseres Wording finden. Hier sollte es auch die Möglichkeit geben, separat den „Profigrad“ öffentlich/privat zu markieren. (SIEHE ANDERES TICKET DAZU) Die ausgewählten Spiele sollten immer angezeigt werden

**Comment by leganz** [comment]
Fixed
