### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#6]
Kontaktseite oder Kontakt bei About angeben?

**Comment by natiie** [comment]
Cool. Seiten erstellen hat funktioniert. Aber Seite wird dann nicht im Menü angezeigt. Hab https://www.league-of-girls.com/kontakt mal erstellt zum Testen.

**Comment by natiie** [comment]
About hab ich jetzt auch erstellt. Ich kann dann die Seiten auch aufrufen wenn ich mit dem Admin eingeloggt bin. Wenn ich mich mit meinem einlogge, dann kommt nichts. Also der Seiteninhalt wird gar nicht angezeigt. 
https://www.league-of-girls.com/about

**Comment by leganz** [comment]
@natiie => die einzelnen Elemente müssen ebenfalls veröffentlicht werden.

**Comment by natiie** [comment]
Ah ok passt! Die erstellten Seiten sehe ich noch immer nicht im Menü. Sollten die unten in die Menüleiste kommen am besten oder?

**Comment by leganz** [comment]
ist jetzt nach unten gewandert -> @natiie - bitte testen.
