### ISSUE TITLE
Suchfunktion News

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#62]
Im News Bereich braucht es eine Such- bzw. Filterfunktion. Gut wäre es wahrscheinlich nach Kategorien filtern zu können oder generell etwas anders zu strukturieren. Also z.B.: Ich lass mir nur Artikel anzeigen oder nur Twitch Kanäle. 

Feedback von Yvonne:
Unübersichtliche Strukturierung. Zeitstempel wäre hier wichtig. Farbliche Unterteilung gefällt mir. Idee: Einteilung in drei spalten? Evtl. Twitch separat in eine abgetrennte rechte Spalte erfassen, Mittlere Spalte „Social Media“ Kanäle der Gamerinnen (wenn erwünscht – Einstellungen der Profiluser). Links „news“ interessante Seiten, Infos posten. Unterteilung in dieser Rubrik wichtig sonst sehr unübersichtlich.

**Comment by natiie** [comment]
Hier relevant auch das Filtern von "Featured" Beiträgen. Momentan gehen die komplett unter.

**Comment by leganz** [comment]
Suchfunktion wurde implementiert. Hinzugekommen sind auch Funktionen zum Filtern von "Merklistenbeiträgen" und gefeatureden Beiträgen.
