### ISSUE TITLE
Anzeige, mit wem man befreudet ist

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#66]
Vorschlag von Yvonne:
Freunde/Folgschaft – kann man öffentlich im Profil sehen (wer wem folgt bzw. wer mit wem befreundet ist) falls ja wo wird dies angezeigt, direkt unter dem Profilbild, unten nach den Links? Positionierung wichtig. 

...
So etwas wie Folgen haben wir ja nicht. Aber im Sinne von Netzwerk aufbauen wäre es wahrscheinlich gut, wenn man sieht, mit wem sich Leute verknüpft haben.

**Comment by leganz** [comment]
Freundeslisten wurden implementiert. Auch zahlreiche kleinere Fehler im Zusammenhang mit dem Connectbutton wurden aus der Welt geschafft.
