### ISSUE TITLE
Chat Funktionen

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#67]
Ausbau notwendig?

Kommentar von Yvonne:

Chat
Was ist hier angedacht? Alle Leute online können hier im gemeinsamen Chatroom schreiben ? Falls ja – Ordnerstruktur überlegen, Themenspezifisch wenige Räume erstellen? Zusatzidee. Teamspeak anbieten mit Ordnerstruktur?

**Comment by leganz** [comment]
Problem sollte beseitigt sein. Es war lediglich eine fehlerhafte Konfiguration am Testsystem schuld.
