### ISSUE TITLE
Unterscheidung Gamerin und anderen 

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#68]
Die Plattform soll ja grundsätzlich für alle offen sein. Also es können sich ja auch Menschen registrieren, die keine eSportlerin oder proGamerin sind. z.B. Person, die im E-Sport Event organisiert. Oder eine Spieleforscherin. Oder einfach Personen, natürlich auch Männer, die sich für die Förderung im E-Sport einsetzen möchten.
Diese Personen sind im Sinne von Netzwerk / Community genauso wichtig, wie nur die Gamerinnen. Es wäre aber wahrscheinlich gut im Profil die Leute grob in unterschiedliche Kategorien einzuteilen (nach denen dann auch gefiltern werden kann), z.B.: Gamerin, Gamer, sonst. Personen aus E-Sport, Gaming-Branche, Forschung, Journalismus... (Wording müsst ma noch schauen)

Das hätte dann auch zum Vorteil, dass wir folgendes Feature einführen können:
Bei "Gamerin" kann (wenn von User gewünscht) der Twitter, Twitch etc. Kanal automatisch in die News-Sektion gepusht werden. 

Außerdem macht es auch im Sinne von Netzwerk aufbauen Sinn. Also könnte ich z.B. als Gamerin nach Journalist*innen suchen oder eben umgekehrt. Am eSport Summit ist das Thema aufgekommen, dass es für JournalistInnen sehr schwierig ist, einzelne E-Sportler*innen zu finden (für Presseanfrage oder Foto).

Was haltet ihr davon? Fände das sehr sinnvoll :)

**Comment by leganz** [comment]
Es gibt nun zahlreiche weitere Untescheidungsmerkmale. Kriterien können definiert werden welche der Benutzer dann auswählen kann. Anhand dieser Informationen kann er auch gesucht werden.
