### ISSUE TITLE
Gamerinnen Liste bei Spielbereichen im News Channel

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#71]
Vorschlag von Yvonne: 
Hier eine Idee: Rechte Seite eine Liste der Gamerinnen die im Profil hier zB Call of Duty angegeben haben mit Verweislink auf deren Profil. Liste immer random durchgemischt, bei neuem Laden der Seite wieder neu angeordnete Namensliste.

**Comment by leganz** [comment]
Wurde durch PP abgelehnt.
