### ISSUE TITLE
Aktuell funktioniert die Seite gar nicht

### ISSUE THREAD

**Issue by rranzmaier** [PICAPIPE/league-of-girls#72]
Permanente Fehler 500 beim Aufruf von https://league-of-girls.com:6001/socket.io/?EIO=3....

Getested mit Edge und Chrome

![image](https://user-images.githubusercontent.com/7863837/45816859-2f2be400-bcdd-11e8-9dc5-71cbda2a6915.png)

**Comment by leganz** [comment]
Danke. Wir sehen uns das gleich an. Es handelt sich aber nur um die Verbindung zum Websocket die automatische Aktualisierungen zum Client vom Server schickt.
Die Seite ist natürlich an den anderen Stellen sehr wohl funktionstüchtig.

**Comment by leganz** [comment]
Fehler behoben.
