### ISSUE TITLE
Anzeige "Featured" Beiträge

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#73]
Es wird nur ein "Featured" Beitrag im nicht eingeloggten Zustand auf der Landing Page angezeigt. Sonst sind Featured Beiträg nicht ersichtlich. Siehe auch Ticket zur Suchfunktion News: https://github.com/PICAPIPE/league-of-girls/issues/62

**Comment by leganz** [comment]
Die Startseite wurde komplette neu gestaltet. Auch die angemeldete Version ist davon betroffen.
