### ISSUE TITLE
Mehr Spiele?

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#8]
Ich wirf hier jetzt mal die Frage auf, ob wir noch mehr Spiele einbinden wollen links. Wäre grundsätzlich mögich oder?

**Comment by leganz** [comment]
@monotonist, @natiie  bitte testen
Admin-Konto kann neue Spiele, Plattformen, Linktypen, Kommunikationsmethoden hinzufügen

**Comment by natiie** [comment]
Wenn ich ein neues Spiel eintragen will als Admin, kommt die Meldung, ich habe nicht ausreichend Berechtigungen. 
Und was gehört bei CSS Klasse rein?

**Comment by leganz** [comment]
@natiie sollte jetzt behoben sein.
CSS-Klasse (Icon)
Entweder aus unserer Icon-Font (die momentan keine hat)
Oder von Font-Aweseome.
Müssen dann wohl noch Icons für die Spiele nachliefern.
