### ISSUE TITLE
Bei verbundenen Usern steht noch immer Anfrage

### ISSUE THREAD

**Issue by natiie** [PICAPIPE/league-of-girls#9]
Meet - Nach Verbunden, steht noch immer Anfrage
Ich kann auch noch immer auf Verbinden klicken, dann kommt Fehlermeldung, weil bereits Verbindung besteht

**Comment by leganz** [comment]
Button wird nicht mehr angezeigt bzw. nach "Anfrage" wird in er Meet Liste der Button ausgeblendet.

**Comment by natiie** [comment]
Hat jetzt bei neuer Anfrage funktioniert. Aber bei Admin-Konto, mit dem ich schon verbunden bin, steht noch immer Anfrage und es kommt diesselbe Fehlermeldung (also so wie oben)

**Comment by leganz** [comment]
Ist am Echtsystem verfügbar. 
Wurde im Workflow noch etwas verbessert.

**Comment by natiie** [comment]
Hatte noch immer den Fehler. Aber hab jetzt Admin und mich neu befreundet, jetzt klappts.
